### ISSUE TITLE
Process is OOMKilled by the system

### ISSUE THREAD

**Issue by alexandreroman** [cloudfoundry-tutorials/korifi-sample-app#1]
The default memory configuration set in the manifest is not enough.
It turns out that `32M` is not enough to run the app on my workstation (laptop: Mac M1).

Increasing the value to `64M` seems to fix the issue.

```
---
applications:
  - name: sample-app
    instances: 1
    memory: 64M
    disk_quota: 64M
    path: ./src
```
